In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [36]:
df = pd.read_csv("/Users/fionaaaaa_mei/Downloads/august_2023_searches.csv")
df.head(5)

dt  institutional_affiliation  \
0  2023-08-03                      False   
1  2023-08-25                       True   
2  2023-08-12                      False   
3  2023-08-31                       True   
4  2023-08-25                      False   

                                           metric_id  \
0  Searches_Platform_3d33f627-3ad0-4e7e-9832-7390...   
1  Searches_Platform_0c60725b-87d3-49ed-bb1b-0b66...   
2  Searches_Platform_786def01-bdf1-4d6a-adda-c5c8...   
3  Searches_Platform_b5f671cd-d299-402b-9067-5092...   
4  Searches_Platform_35ef3849-f2be-4d8d-8911-3afe...   

                    personal_account_id   search_type query_string  \
0  c6cefc2a-6d0a-4f3e-9e1e-7bc6b27ac5f9  basic_search          NaN   
1                                   NaN  basic_search          NaN   
2                                   NaN  basic_search          NaN   
3                                   NaN  basic_search          NaN   
4                                   NaN  basic_search          NaN   

                              requestid                    auth_sessionid  
0  14c47cd5-9d31-fee3-cfce-76d9b7214ac3  94f1a3263a6348f1bf7ffbd6d8c39c05  
1  1525f88f-dcc4-58a7-580a-9e2e2ad06768  818df6122523486181e3619ea694095c  
2  1b4c0339-e625-133a-ced9-8eaa7fe09695  9f98b93cdd964f5fb54363336fded27a  
3  1f9fcf72-f889-466f-8ac8-4e0066d55b16  87d139d379264f61b247bab366411388  
4  2307d346-05b1-c826-6a92-f1732ed22fb2  cf99c55f8014455c8ce8b0301741da7e

In [37]:
df = df.dropna(subset=['query_string'])


In [38]:
df.head(5)

dt  institutional_affiliation  \
24  2023-08-07                       True   
25  2023-08-29                      False   
26  2023-08-17                      False   
27  2023-08-30                       True   
28  2023-08-21                      False   

                                            metric_id  \
24  Searches_Platform_cd11029c-37bf-42f5-8284-1d3f...   
25  Searches_Platform_af5d01f0-58d4-4153-bda5-c915...   
26  Searches_Platform_b1d6a3f7-5bda-489f-821c-4e7e...   
27  Searches_Platform_271f3c55-45b6-4f5f-9327-5549...   
28  Searches_Platform_1659c830-ca36-499b-bfe7-b176...   

                     personal_account_id   search_type  \
24                                   NaN  basic_search   
25  d30ed7fe-6536-4261-9b1c-5d127ca2390e  basic_search   
26  e828e177-21ab-4a57-8a85-49789d028ff2  basic_search   
27                                   NaN  basic_search   
28  3bd26986-75de-4dfc-8c03-7847910d7353  basic_search   

                                         query_string  \
24                                        Child abuse   
25  1.\tAhmad, N., & Hassan, R. (2015). The effect...   
26                    gather ye rosebuds while ye may   
27  [Nicolaas van der Waay (1855-1936): A Dutch Pa...   
28                                      car pollution   

                                          requestid  \
24  fastly-default:00032f2cdcc9e112559ce0f44451d869   
25  fastly-default:0003926a918f974401fce8e9993c3767   
26  fastly-default:0007f21549b981eec2f85e013f260023   
27  fastly-default:00094239ffc0c12e40e10b2ec18941ce   
28  fastly-default:000ff57e598d821597179d943571f3ce   

                      auth_sessionid  
24  df2c17513cb64824b246e84cea5475e3  
25  89098123304e450295305f421b93f438  
26  5bef5573e2f944869b2cd9da411228ec  
27  8a6f7a9476934f01b8baa39abd2967fd  
28  3442c7b38f5148339a27c4fc0fca6f91

In [39]:
#Remove stop words and rejoin list of words
#Lifted from https://medium.com/@yashj302/stopwords-nlp-python-4aa57dc492af

stopwords = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
              'ourselves', 'you', 'your', 'yours', 'yourself',
              'yourselves', 'he', 'him', 'his', 'himself', 'she',
              'her', 'hers', 'herself', 'it', 'its', 'itself',
              'they', 'them', 'their', 'theirs', 'themselves',
              'what', 'which', 'who', 'whom', 'this', 'that',
              'these', 'those', 'am', 'is', 'are', 'was', 'were',
              'be', 'been', 'being', 'have', 'has', 'had', 'having',
              'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and',
              'but', 'if', 'or', 'because', 'as', 'until', 'while',
              'of', 'at', 'by', 'for', 'with', 'about', 'against',
              'between', 'into', 'through', 'during', 'before',
              'after', 'above', 'below', 'to', 'from', 'up', 'down',
              'in', 'out', 'on', 'off', 'over', 'under', 'again',
              'further', 'then', 'once', 'here', 'there', 'when',
              'where', 'why', 'how', 'all', 'any', 'both', 'each',
              'few', 'more', 'most', 'other', 'some', 'such', 'no',
              'nor', 'not', 'only', 'own', 'same', 'so', 'than',
              'too', 'very', 'should', 'can', 'now', 'will', 'just',
              'would', 'could', 'may', 'must', 'one', 'much', "it's",
              "can't", "won't", "don't", "shouldn't", "hasn't"]

#
                              'ourselves', 'you', 'your', 'yours', 'yourself',
                              'yourselves', 'he', 'him', 'his', 'himself',
                              'she', 'her', 'hers', 'herself', 'it', 'its',
                              'itself', 'they', 'them', 'their', 'theirs',
                              'themselves','which', 'who', 'whom', 'this',
                              'that', 'these', 'those', 'what', 'a', 'an',
                              'the', 'and', 'but', 'if', 'or', 'because',
                              'as', 'of', 'at', 'by', 'for', 'with', 'about',
                              'against', 'between', 'into', 'through', 'above',
                              'below', 'to', 'from', 'up', 'down', 'in', 'out',
                              'on', 'off', 'over', 'under', 'again', 'further',
                              'here', 'there', 'all', 'any', 'both', 'each',
                              'few', 'more', 'most', 'other', 'some', 'such',
                              'no', 'nor', 'not', 'only', 'own', 'same', 'so',
                              'than', 'too', 'very', 'one', 'much', "it's",
                              "can't", "won't", "don't", "shouldn't", "hasn't"]

#set for memory optimization
stopwords = set(stopwords)


In [40]:
def clean_string(string):
    return ''.join(char.lower() for char in string if char.isalpha() or char.isspace())

def remove_word(string):
    words = string.split()
    return ' '.join(word for word in words if word not in stopwords_temporal_removed)


In [41]:
remove_word(clean_string("A hate you"))

'hate'

In [42]:
clean_string(remove_word("I Hate you"))

'i hate'

In [43]:
df['query_string'] = df['query_string'].apply(clean_string).apply(remove_word)

In [44]:
df.head()

dt  institutional_affiliation  \
24  2023-08-07                       True   
25  2023-08-29                      False   
26  2023-08-17                      False   
27  2023-08-30                       True   
28  2023-08-21                      False   

                                            metric_id  \
24  Searches_Platform_cd11029c-37bf-42f5-8284-1d3f...   
25  Searches_Platform_af5d01f0-58d4-4153-bda5-c915...   
26  Searches_Platform_b1d6a3f7-5bda-489f-821c-4e7e...   
27  Searches_Platform_271f3c55-45b6-4f5f-9327-5549...   
28  Searches_Platform_1659c830-ca36-499b-bfe7-b176...   

                     personal_account_id   search_type  \
24                                   NaN  basic_search   
25  d30ed7fe-6536-4261-9b1c-5d127ca2390e  basic_search   
26  e828e177-21ab-4a57-8a85-49789d028ff2  basic_search   
27                                   NaN  basic_search   
28  3bd26986-75de-4dfc-8c03-7847910d7353  basic_search   

                                         query_string  \
24                                        child abuse   
25  ahmad n hassan r effects external funding sust...   
26                    gather ye rosebuds while ye may   
27  nicolaas van der waay dutch painter fin de siècle   
28                                      car pollution   

                                          requestid  \
24  fastly-default:00032f2cdcc9e112559ce0f44451d869   
25  fastly-default:0003926a918f974401fce8e9993c3767   
26  fastly-default:0007f21549b981eec2f85e013f260023   
27  fastly-default:00094239ffc0c12e40e10b2ec18941ce   
28  fastly-default:000ff57e598d821597179d943571f3ce   

                      auth_sessionid  
24  df2c17513cb64824b246e84cea5475e3  
25  89098123304e450295305f421b93f438  
26  5bef5573e2f944869b2cd9da411228ec  
27  8a6f7a9476934f01b8baa39abd2967fd  
28  3442c7b38f5148339a27c4fc0fca6f91

In [47]:
def query_length(query):
    if len(query) > 5:
        return "long"
    return "short"

In [45]:
pip install -U sentence-transformers

Note: you may need to restart the kernel to use updated packages.


In [78]:
from sentence_transformers import SentenceTransformer
sentences = df['query_string'].tolist()
sentences = sentences[0:10000]

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
embeddings = model.encode(sentences)
print(embeddings)

KeyboardInterrupt: 

In [75]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = similarity = cosine_similarity(embeddings, embeddings)
similarity

array([[ 1.00000024e+00,  6.00022115e-02,  6.10139631e-02, ...,
         1.11107536e-01,  2.83833772e-01,  3.36013049e-01],
       [ 6.00022115e-02,  1.00000012e+00, -6.97791800e-02, ...,
         1.65645376e-01,  2.48845425e-02,  1.87191740e-02],
       [ 6.10139631e-02, -6.97791800e-02,  1.00000000e+00, ...,
        -1.68380309e-02,  1.09538764e-01,  5.54632694e-02],
       ...,
       [ 1.11107536e-01,  1.65645376e-01, -1.68380309e-02, ...,
         1.00000000e+00, -4.15358692e-04, -2.49168091e-02],
       [ 2.83833772e-01,  2.48845425e-02,  1.09538764e-01, ...,
        -4.15358692e-04,  1.00000024e+00,  6.93451762e-02],
       [ 3.36013049e-01,  1.87191740e-02,  5.54632694e-02, ...,
        -2.49168091e-02,  6.93451762e-02,  1.00000000e+00]], dtype=float32)

In [ ]:
result = {}
for i in range(len(similarity)):
    

In [59]:
from transformers import AutoTokenizer, AutoModel
import torch
import torch.nn.functional as F
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/all-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/all-mpnet-base-v2')

def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

# Normalize embeddings
sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)

print("Sentence embeddings:")
print(sentence_embeddings)

Sentence embeddings:
tensor([[-1.3081e-02, -3.0887e-03,  9.9356e-03,  2.5945e-02,  1.7544e-02,
          1.7259e-02, -8.9481e-03,  9.2967e-03,  4.0810e-03,  2.1503e-02,
         -8.4300e-03,  6.5115e-02,  2.3292e-02, -7.3931e-03,  6.6806e-03,
          4.0605e-03, -5.5216e-03, -6.0035e-03,  3.8435e-02, -4.3108e-03,
          1.2339e-02,  1.7104e-02,  2.2402e-02,  4.8841e-02,  6.3238e-02,
          8.6374e-03, -1.9316e-02,  2.8212e-02, -4.8609e-02,  9.0360e-03,
          1.9076e-02,  8.5810e-03,  1.6533e-02, -7.6406e-03,  1.7538e-06,
          1.5360e-02, -2.8907e-02,  1.5209e-03,  1.3755e-02, -2.0205e-02,
          2.8680e-02, -1.3209e-02, -2.0372e-02, -1.5390e-02,  7.3954e-04,
         -6.6736e-03,  4.8000e-02, -4.9933e-02, -5.6546e-02,  2.5208e-02,
          3.1560e-03, -1.6832e-02, -9.6703e-03,  9.1974e-03,  3.2618e-02,
          1.6189e-02,  3.4066e-03, -3.1438e-04,  1.7028e-02,  3.4267e-02,
         -3.5247e-02, -3.0119e-03, -3.5470e-02, -1.8167e-02,  1.1946e-02,
          2.9224e

In [66]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = similarity = cosine_similarity(embeddings, embeddings)
similarity

array([[ 1.,  1., -1., ...,  1.,  1.,  1.],
       [ 1.,  1., -1., ...,  1.,  1.,  1.],
       [-1., -1.,  1., ..., -1., -1., -1.],
       ...,
       [ 1.,  1., -1., ...,  1.,  1.,  1.],
       [ 1.,  1., -1., ...,  1.,  1.,  1.],
       [ 1.,  1., -1., ...,  1.,  1.,  1.]], dtype=float32)